version: '3.8'

services:
  vue-notes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: vue-notes-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount nginx config for development
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add a development service
  vue-notes-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: vue-notes-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev